# Travis-CI Build for koreader-base
# see travis-ci.org for details

dist: xenial
sudo: required

service:
  - docker

cache:
  apt: true
  directories:
    - $HOME/.ccache

env:
  matrix:
    - SHELLCHECKS=1
    - EMULATE_READER=1 CC=gcc
    - EMULATE_READER=1 CC=gcc USE_MAKE=1
    - EMULATE_READER=1 CC=gcc KODEBUG=1
    - EMULATE_READER=1 CC=clang

addons:
  apt:
    packages:
      - cmake
      - ninja-build
      - g++
      - libsdl2-dev
      - luajit
      - luarocks
      # for luasec
      - libssl1.0.0
      - nasm
      # OpenSSL likes this (package contains makedepend)
      - xutils-dev
      # libzmq workaround because we're using a positively ancient version, see https://github.com/zeromq/libzmq/pull/1497
      - libtool-bin

install:
  - if [ "$EMULATE_READER" = 1 ]; then source .ci/emulator_install.sh; fi
  - if [[ -n ${DOCKER_IMG+x} ]]; then docker pull $DOCKER_IMG; fi

script:
  - if [ "$EMULATE_READER" = 1 ]; then source .ci/test_script.sh; fi
